### ISSUE TITLE
Questions about Korean models

### ISSUE THREAD

**Issue by 0913ktg** [litagin02/Style-Bert-VITS2#18]
Hello 'litagin02',

I hope this message finds you well. I am currently working on implementing and training the Style-Bert-VITS2 in Korean, using 'fishaudio's Bert-VITS2 repository as a basis. However, due to the lack of specific information on the Korean adaptation, I am unsure if my approach is correct.

I understand that the Style-Bert-VITS2 utilizes the pre-trained model from Bert-VITS2. My query pertains to the meaning of 'emo-related key in G_0 deleted.' Specifically, I am uncertain whether this implies that the training of Bert-VITS2 should exclude emotion-related content or if it involves training with emotion aspects and then omitting the emotion-related key during loading.

Additionally, I am curious about the extent to which the pre-trained model should be trained for optimal results.

Your insights on these matters would be greatly appreciated. Thank you for your time and assistance. Wishing you a pleasant day.

Best regards.

**Comment by litagin02** [comment]
Thank you for questions.

> the meaning of 'emo-related key in G_0 deleted.' 

This is about how I made the *pretrained* model of Style-Bert-VITS2 from Bert-VITS2 2.1's original pretrained model.

There's emotion embedding in Bert-VITS2 2.1, and it's in TextEncoder's `self.emo_proj` and some other parts:
https://github.com/litagin02/Style-Bert-VITS2/blob/fb43a178a38b88ec6942ba97770eead3a8de6955/models_V210.py#L350-L359

 But since I think this does not work well, I decided to use other emotion (style) embedding and other approach. But other parts than emo-embeddings are the same as 2.1, so we can use the Bert-VITS2 2.1 pretrained model.
So I just deleted `emo_proj` and some other keys in the pretrained model of Bert-VITS2 2.1 because it's unused in Style-Bert-VITS2.

So as for Style-Bert-VITS2, basically in the train (using pretrained model), it is recommended to use voices with rich emotions (since bert and our new style embeddings can capture emotions (styles)). As for the original Bert-VITS2, it's still recommended I think because bert seems to be capture emotions very well.

> Additionally, I am curious about the extent to which the pre-trained model should be trained for optimal results.

I don't know because I just borrowed pretrained model from Bert-VITS2 2.1, and I haven't trained from scratch. Maybe you should consult Bert-VITS2's developer Fish Speech or some information could be found on:
https://github.com/fishaudio/Bert-VITS2/pull/245
