### ISSUE TITLE
Errors in reading

### ISSUE THREAD

**Issue by Kamikadashi** [litagin02/Style-Bert-VITS2#25]
There are a lot of errors when converting text into its reading.

Examples of problematic sentences:
そんな事を訊くなんて、まったく彼女らしくない。
自分の勘の良さに嗤ってしまう。
「誘おうと思ったんだけど教室行ったらもういなかったんだよ」
いやいや、オレはついこの間まで男だったヤツだぞ。
「人がいたりしてな」
正直あんな風にされるぐらいなら…………。
どういう風に変化ったのじゃ。
この方が、集中治療施設に移送された、と。

**Comment by litagin02** [comment]
> 自分の勘の良さに嗤ってしまう。
This raises error because pyopenjtalk cannot read "嗤って", so you have to replace it (in this case, "笑って" may be appropriate).

I think other statements do not raise error and can be synthesized or trained, but have errors in how to read Kanji. It's a problem of pyopenjtalk, so I don't have any solutions except for manually replacing ambiguous Kanjis with more readable Kanji or Hiragana, like 「いやいや、オレはついこのあいだまで男だったヤツだぞ。」.
